sdx85 : Support for dm-verity
Added changes for dm-verity and initramfs changes for verification

Change-Id: Ib0b50c318b46dc74db097295bc33426cbf51045a

diff --git a/bsp-packages/rd-init/files/init b/bsp-packages/rd-init/files/init
--- a/bsp-packages/rd-init/files/init
+++ b/bsp-packages/rd-init/files/init
@@ -87,15 +87,20 @@ else
             fi
         fi
     done
-    echo "Mounting the system partition"
-    /bin/mount -t ext4 -o ro "$partition" /mnt/system || {
-    if [ "$DEBUG" = "1" ]; then
-        echo "Mount failed for $partition"
-        start_rdshell
+    verityenabled=$(cat /proc/cmdline | grep -o 'verity=enabled')
+    if [ "$verityenabled" ]; then
+        ./init_verity.sh $partition
     else
-        /sbin/reboot -f
+        echo "Mounting the system partition"
+        /bin/mount -t ext4 -o ro "$partition" /mnt/system || {
+        if [ "$DEBUG" = "1" ]; then
+            echo "Mount failed for $partition"
+            start_rdshell
+        else
+            /sbin/reboot -f
+        fi
+        }
     fi
-    }
 fi
 
 echo "Switching to system partition"
